apiVersion: extensions/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  namespace: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: phpmyadmin/phpmyadmin
          imagePullPolicy: Always
          name: phpmyadmin
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            # alternative to PMA_HOSTS, but need to add server in phpmyadmin ui
            # - name: PMA_ARBITRARY
              # value: '1'
            - name: PMA_HOSTS
              value: mysql-0.namespace-name:3306

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  namespace: database
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - port: 30080
      nodePort: 30080
      targetPort: 80
