version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
      - MYSQL_DATABASE=team-member-projects
      # make all values configurable
      # - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOSTS=mysql
