---
- name: Install java and net-tools
  hosts: "{{ variable_host }}"
  roles:
    - install-legacy-java

- name: Download and unpack Nexus installer
  hosts: "{{ variable_host }}"
  roles:
    - download-untar-nexus

- name: Create nexus user to own nexus folder
  hosts: "{{ variable_host }}"
  roles:
    - create-permit-nexus-user

- name: Start nexus with nexus user
  hosts: "{{ variable_host }}"
  become: True
  become_user: "{{ service_user }}"
  roles:
    - start-nexus-binary

- name: Verify nexus running
  hosts: "{{ variable_host }}"
  roles:
    - check-nexus-availability