- name: Install python dependencies for aws ec2 dynamic inventory plugin
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-boto3
      - python3-packaging
      - python3-botocore
    state: latest
    update_cache: true
    force_apt_get: yes
    cache_valid_time: "{{ apt_cache_valid_seconds }}"

