---
- name: Install node and npm
  hosts: "{{ variable_host }}"
  become: true
  roles:
    - install-node-npm

# see https://docs.ansible.com/ansible-core/2.17/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
- name: Install ACL so ansible works for non-root users
  hosts: "{{ variable_host }}"
  become: true
  roles:
    - install-acl-for-non-root-users

- name: Create new linux user for node app
  become: true
  become_method: sudo
  hosts: "{{ variable_host }}"
  roles:
    - create-linux-user

- name: Deploy nodejs app
  hosts: "{{ variable_host }}"
  become: true
  become_method: sudo
  become_user: "{{ linux_user }}"
  vars:
    user_home_dir: "/home/{{ linux_user }}"
    node_dir: "/home/{{ linux_user }}/package"
    app_dir: "/home/{{ linux_user }}/package/app"
  roles:
    - deploy-node-app