pipeline {
  agent any
  environment {
    ANSIBLE_CONTROL_NODE_IP = "172.104.237.64"
    JAVA_VERSION = "2.0"
  }
  stages {
    stage("Git Checkout SCM") {
      steps {
        git branch: 'main', credentialsId: 'git-creds', url: 'https://github.com/hangrybear666/15-devops-bootcamp__ansible.git'
      }
    }

    stage("copy files to ansible server") {
      steps {
        dir('07-jenkins-ansible-integration') {
          script {
            echo "copying all neccessary files to ansible control node"
            sshagent(['control-node-pk']) {
              // copy entire ansible work directory to control node
              sh "scp -o StrictHostKeyChecking=no -r ./* root@${ANSIBLE_CONTROL_NODE_IP}:/root/07-jenkins-ansible-integration"
              // copy java-app .env file to control node
              withCredentials([file(credentialsId: 'ansible-java-app-env', variable: 'env')]) {
                  sh 'scp -o StrictHostKeyChecking=no $env root@${ANSIBLE_CONTROL_NODE_IP}:/root/07-jenkins-ansible-integration/roles/build-and-push-to-ecr/files/java-app/.env'
              }

              // copy private key file for ssh access to target deployment servers
              withCredentials([sshUserPrivateKey(credentialsId: 'ec2-targets-pk', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                sh 'scp $keyfile root@$ANSIBLE_CONTROL_NODE_IP:/root/.ssh/ec2-targets-pk'
              }
            }
          }
        }
      }
    }
    stage("execute ansible playbook") {
      steps {
        dir('07-jenkins-ansible-integration') {
          script {
            echo "executing ansible playbook on control node"
            def controlNode = "root@${ANSIBLE_CONTROL_NODE_IP}"
            sshagent(['control-node-pk']) {
              sh """
              ssh -o StrictHostKeyChecking=no ${controlNode} "
                source /root/.venv/bin/activate
                cd /root/07-jenkins-ansible-integration
                ansible-playbook site.yaml -e java_app_version=${JAVA_VERSION}
                deactivate
                "
              """
            }
          }
        }
      }
    }
  }
}
