pipeline {
  agent any
  environment {
    ANSIBLE_SERVER = "172.104.139.219"
    JAVA_VERSION = "2.0"
  }
  stages {
    stage("Git Checkout SCM") {
      steps {
        git branch: 'main', credentialsId: 'git-creds', url: 'https://github.com/hangrybear666/15-devops-bootcamp__ansible.git'
      }
    }

    stage("copy files to ansible server") {
      steps {
        dir('07-jenkins-ansible-integration') {
          script {
            echo "copying all neccessary files to ansible control node"
            sshagent(['control-node-pk']) {
              sh "scp -o StrictHostKeyChecking=no -r ./* root@${ANSIBLE_SERVER}:/root/07-jenkins-ansible-integration"

              withCredentials([sshUserPrivateKey(credentialsId: 'ec2-targets-pk', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                sh 'scp $keyfile root@$ANSIBLE_SERVER:/root/.ssh/ec2-targets-pk.pem'
              }
            }
          }
        }
      }
    }
    stage("execute ansible playbook") {
      steps {
        dir('07-jenkins-ansible-integration') {
          script {
            echo "executing ansible playbook on control node"
            def controlNode = "root@${ANSIBLE_SERVER}"
            def shellCmd = """
            ansible-playbook site.yaml -e java_app_version="${JAVA_VERSION}"
            """
            sshagent(['control-node-pk']) {
              sh "ssh -o StrictHostKeyChecking=no ${controlNode} ${shellCmd}"
            }
          }
        }
      }
    }
  }
}
