---
# - name: Get AWS credentials & login to ECR repository
#   hosts: localhost
#   roles:
#     - aws-docker-login-ecr

# - name: Build local image & push it to a ECR repo
#   hosts: localhost
#   roles:
#     - build-and-push-to-ecr

- name: Create new linux user for docker
  become: true
  become_method: sudo
  hosts: all
  roles:
    - create-permit-docker-user

- name: Install Docker & Docker Compose
  hosts: all
  become: yes
  vars:
    debian_docker_distro_url: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
  roles:
    - install-docker-and-compose

# - name: Start docker containers
#   hosts: docker_server
#   vars_files:
#     - project-vars
#   tasks:
#     - name: Copy docker compose
#       copy:
#         src: /Users/nana/bootcamp-java-mysql-project/docker-compose-full.yaml
#         dest: /home/ec2-user/docker-compose.yaml
#       docker_login:
#         username: nanatwn
#     - name: Docker login
#         password: "{{docker_password}}"
#     - name: Start containers from compose
#       community.docker.docker_compose_v2:
#         project_src: /home/ec2-user
