- name: Remove prior docker installations
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
    state: absent

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg2
    state: latest
    update_cache: true
    force_apt_get: yes

- name: Create Docker keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "{{ debian_docker_distro_url }}"
    state: present

- name: Update apt and install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
    force_apt_get: yes
    cache_valid_time: "{{ apt_cache_valid_seconds }}"

- name: Start docker daemon
  ansible.builtin.systemd_service:
    name: docker
    state: started