services:

  mysqldb:
    image: mysql:9.0.1
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - mysql-db-gui
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute \"SELECT 1\""]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: always
    ports:
      - 8085:80
    networks:
      - mysql-db-gui
    links:
      - mysqldb:db
    depends_on:
      mysqldb:
        condition: service_healthy
  
  java-app:
    image: java-app:${VERSION_TAG}
    container_name: java-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_SERVER=${DB_SERVER_OVERRIDE}
    ports:
      - 80:8080
    networks:
      - mysql-db-gui
    depends_on:
      mysqldb:
        condition: service_healthy

networks:
  mysql-db-gui:
    driver: bridge

volumes:
  mysql-data:
    name: mysql-data