- name: Update apt repo and cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: "{{ apt_cache_valid_seconds }}"
- name: Install nodejs and npm
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm
